  name: CI

  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

  jobs:
    test:
      strategy:
        matrix:
          config: [
            { target: jvm, os: ubuntu-latest, tasks: jvmTest, continueOnError: false },
            { target: apple, os: macos-latest, tasks: iosX64Test iosSimulatorArm64Test, continueOnError: false },
          ]
      runs-on: ${{ matrix.config.os }}
      steps:
        # Cancel any previous runs for the same branch that are still running.
        - name: 'Cancel previous runs'
          uses: styfle/cancel-workflow-action@0.11.0
        - uses: actions/checkout@v3
        - name: 'Setup gradle'
          uses: gradle/gradle-build-action@v2
          with:
            access_token: ${{ github.token }}
        - name: 'Set up JDK 17'
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu'
        - name: Test ${{ matrix.config.target }} targets
          continue-on-error: ${{ matrix.config.continueOnError }}
          run: ./gradlew ${{ matrix.config.tasks }}
